from enum import StrEnum


class AuditAction(StrEnum):
    AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS"
    AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE"
    AUTH_LOGOUT = "AUTH_LOGOUT"
    AUTH_PASSWORD_CHANGE = "AUTH_PASSWORD_CHANGE"
    AUTH_REFRESH = "AUTH_REFRESH"
    AUTH_REFRESH_REUSE_DETECTED = "AUTH_REFRESH_REUSE_DETECTED"
    AUTH_PASSWORD_RESET_REQUESTED = "AUTH_PASSWORD_RESET_REQUESTED"
    AUTH_PASSWORD_RESET_COMPLETED = "AUTH_PASSWORD_RESET_COMPLETED"
    AUTH_SESSION_REVOKED = "AUTH_SESSION_REVOKED"
    AUTH_ALL_SESSIONS_REVOKED = "AUTH_ALL_SESSIONS_REVOKED"
    ACCOUNT_DISABLED = "ACCOUNT_DISABLED"
    ACCOUNT_ENABLED = "ACCOUNT_ENABLED"

    USER_CREATED = "USER_CREATED"
    USER_UPDATED = "USER_UPDATED"
    USER_DISABLED = "USER_DISABLED"
    USER_ROLE_CHANGED = "USER_ROLE_CHANGED"

    PERMISSION_DENIED = "PERMISSION_DENIED"

    PAYMENT_CREATED = "PAYMENT_CREATED"
    PAYMENT_PROOF_UPLOADED = "PAYMENT_PROOF_UPLOADED"
    PAYMENT_SUBMITTED_FOR_REVIEW = "PAYMENT_SUBMITTED_FOR_REVIEW"
    PAYMENT_CONFIRMED = "PAYMENT_CONFIRMED"
    PAYMENT_REJECTED = "PAYMENT_REJECTED"

    QUOTE_CREATED = "QUOTE_CREATED"
    QUOTE_SENT = "QUOTE_SENT"
    QUOTE_VIEWED = "QUOTE_VIEWED"
    QUOTE_ACCEPTED = "QUOTE_ACCEPTED"
    QUOTE_REJECTED = "QUOTE_REJECTED"
    QUOTE_CANCELLED = "QUOTE_CANCELLED"
    QUOTE_EXPIRED = "QUOTE_EXPIRED"

    ORDER_CREATED = "ORDER_CREATED"
    ORDER_STATUS_CHANGED = "ORDER_STATUS_CHANGED"
    ORDER_CANCELLED = "ORDER_CANCELLED"

    PRODUCT_CREATED = "PRODUCT_CREATED"
    PRODUCT_UPDATED = "PRODUCT_UPDATED"
    PRODUCT_PRICE_CHANGED = "PRODUCT_PRICE_CHANGED"
    PRODUCT_PUBLISHED = "PRODUCT_PUBLISHED"
    PRODUCT_ARCHIVED = "PRODUCT_ARCHIVED"

    MATERIAL_CREATED = "MATERIAL_CREATED"
    MATERIAL_UPDATED = "MATERIAL_UPDATED"
    MATERIAL_PRICE_CHANGED = "MATERIAL_PRICE_CHANGED"

    CUSTOMER_CREATED = "CUSTOMER_CREATED"
    CUSTOMER_UPDATED = "CUSTOMER_UPDATED"

    CUSTOM_REQUEST_CREATED = "CUSTOM_REQUEST_CREATED"
    CUSTOM_REQUEST_UPDATED = "CUSTOM_REQUEST_UPDATED"
    CUSTOM_REQUEST_STATUS_CHANGED = "CUSTOM_REQUEST_STATUS_CHANGED"

    FILE_UPLOADED = "FILE_UPLOADED"
    FILE_DELETED = "FILE_DELETED"

    SECURITY_SETTING_CHANGED = "SECURITY_SETTING_CHANGED"
    PAYMENT_CONFIGURATION_CHANGED = "PAYMENT_CONFIGURATION_CHANGED"


class AuditResult(StrEnum):
    SUCCESS = "SUCCESS"
    FAILURE = "FAILURE"
    DENIED = "DENIED"
