from enum import StrEnum


class AuditAction(StrEnum):
    AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS"
    AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE"
    AUTH_LOGOUT = "AUTH_LOGOUT"
    AUTH_PASSWORD_CHANGE = "AUTH_PASSWORD_CHANGE"
    AUTH_REFRESH = "AUTH_REFRESH"
    AUTH_REFRESH_REUSE_DETECTED = "AUTH_REFRESH_REUSE_DETECTED"
    AUTH_PASSWORD_RESET_REQUESTED = "AUTH_PASSWORD_RESET_REQUESTED"
    AUTH_PASSWORD_RESET_COMPLETED = "AUTH_PASSWORD_RESET_COMPLETED"
    AUTH_SESSION_REVOKED = "AUTH_SESSION_REVOKED"
    AUTH_ALL_SESSIONS_REVOKED = "AUTH_ALL_SESSIONS_REVOKED"
    ACCOUNT_DISABLED = "ACCOUNT_DISABLED"
    ACCOUNT_ENABLED = "ACCOUNT_ENABLED"

    USER_CREATED = "USER_CREATED"
    USER_UPDATED = "USER_UPDATED"
    USER_DISABLED = "USER_DISABLED"
    USER_ROLE_CHANGED = "USER_ROLE_CHANGED"

    PERMISSION_DENIED = "PERMISSION_DENIED"

    PAYMENT_CREATED = "PAYMENT_CREATED"
    PAYMENT_PROOF_UPLOADED = "PAYMENT_PROOF_UPLOADED"
    PAYMENT_SUBMITTED_FOR_REVIEW = "PAYMENT_SUBMITTED_FOR_REVIEW"
    PAYMENT_CONFIRMED = "PAYMENT_CONFIRMED"
    PAYMENT_REJECTED = "PAYMENT_REJECTED"
    PAYMENT_CANCELLED = "PAYMENT_CANCELLED"

    QUOTE_CREATED = "QUOTE_CREATED"
    QUOTE_SENT = "QUOTE_SENT"
    QUOTE_VIEWED = "QUOTE_VIEWED"
    QUOTE_ACCEPTED = "QUOTE_ACCEPTED"
    QUOTE_REJECTED = "QUOTE_REJECTED"
    QUOTE_CANCELLED = "QUOTE_CANCELLED"
    QUOTE_EXPIRED = "QUOTE_EXPIRED"

    ORDER_CREATED = "ORDER_CREATED"
    ORDER_STATUS_CHANGED = "ORDER_STATUS_CHANGED"
    ORDER_CANCELLED = "ORDER_CANCELLED"

    PRODUCT_CREATED = "PRODUCT_CREATED"
    PRODUCT_UPDATED = "PRODUCT_UPDATED"
    PRODUCT_PRICE_CHANGED = "PRODUCT_PRICE_CHANGED"
    PRODUCT_PUBLISHED = "PRODUCT_PUBLISHED"
    PRODUCT_ARCHIVED = "PRODUCT_ARCHIVED"
    PRODUCT_VARIANT_CREATED = "PRODUCT_VARIANT_CREATED"
    PRODUCT_VARIANT_UPDATED = "PRODUCT_VARIANT_UPDATED"

    CATEGORY_CREATED = "CATEGORY_CREATED"
    CATEGORY_UPDATED = "CATEGORY_UPDATED"

    MATERIAL_CREATED = "MATERIAL_CREATED"
    MATERIAL_UPDATED = "MATERIAL_UPDATED"
    MATERIAL_PRICE_CHANGED = "MATERIAL_PRICE_CHANGED"
    MATERIAL_PURCHASED = "MATERIAL_PURCHASED"
    MATERIAL_RESERVED = "MATERIAL_RESERVED"
    MATERIAL_RELEASED = "MATERIAL_RELEASED"
    MATERIAL_CONSUMED = "MATERIAL_CONSUMED"
    MATERIAL_ADJUSTED = "MATERIAL_ADJUSTED"
    MATERIAL_RETURNED = "MATERIAL_RETURNED"
    MATERIAL_PRODUCTION_WASTE = "MATERIAL_PRODUCTION_WASTE"
    MATERIAL_INVENTORY_WASTE = "MATERIAL_INVENTORY_WASTE"
    PRODUCTION_ORDER_CREATED = "PRODUCTION_ORDER_CREATED"
    PRODUCTION_ORDER_PLANNED = "PRODUCTION_ORDER_PLANNED"
    PRODUCTION_MATERIALS_RESERVED = "PRODUCTION_MATERIALS_RESERVED"
    PRODUCTION_ORDER_STATUS_CHANGED = "PRODUCTION_ORDER_STATUS_CHANGED"
    PRODUCTION_CONSUMPTION_RECORDED = "PRODUCTION_CONSUMPTION_RECORDED"
    PRODUCTION_WASTE_RECORDED = "PRODUCTION_WASTE_RECORDED"
    PRODUCTION_MATERIAL_RETURNED = "PRODUCTION_MATERIAL_RETURNED"
    PRODUCTION_MATERIAL_RELEASED = "PRODUCTION_MATERIAL_RELEASED"
    PRODUCTION_CANCELLED = "PRODUCTION_CANCELLED"
    PRODUCTION_QUALITY_CHECK_STARTED = "PRODUCTION_QUALITY_CHECK_STARTED"
    PRODUCTION_QUALITY_CHECK_APPROVED = "PRODUCTION_QUALITY_CHECK_APPROVED"
    PRODUCTION_QUALITY_CHECK_REJECTED = "PRODUCTION_QUALITY_CHECK_REJECTED"
    PRODUCTION_COMPLETED = "PRODUCTION_COMPLETED"

    CUSTOMER_CREATED = "CUSTOMER_CREATED"
    CUSTOMER_UPDATED = "CUSTOMER_UPDATED"

    CUSTOM_REQUEST_CREATED = "CUSTOM_REQUEST_CREATED"
    CUSTOM_REQUEST_UPDATED = "CUSTOM_REQUEST_UPDATED"
    CUSTOM_REQUEST_STATUS_CHANGED = "CUSTOM_REQUEST_STATUS_CHANGED"

    FILE_UPLOADED = "FILE_UPLOADED"
    FILE_DELETED = "FILE_DELETED"

    SECURITY_SETTING_CHANGED = "SECURITY_SETTING_CHANGED"
    PAYMENT_CONFIGURATION_CHANGED = "PAYMENT_CONFIGURATION_CHANGED"


class AuditResult(StrEnum):
    SUCCESS = "SUCCESS"
    FAILURE = "FAILURE"
    DENIED = "DENIED"
